export { default as Main} from "./Main"
export { default as Header} from "./Header"
export { default as Footer} from "./Footer"
export { default as Menu} from "./Menu"
export { default as Nosotros} from "./Nosotros"
export { default as Productos} from "./Productos"